version: '3.8'

networks:
  conv_temp_net:
    driver: bridge

services:

  conv_temp:
    container_name: conv_temp
    image: darosas76/conversao-temperatura:v2
    restart: always
    ports:
      - 8080:8080
    networks:
      - conv_temp_net